import StyledComponentsRegistry from '@/lib/registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { DivContainerSC, GlobalStyles, MainSC } from './styles.global'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<StyledComponentsRegistry>
				<GlobalStyles />
				<body className={inter.className}>
					<Header />
					<MainSC>
						<DivContainerSC>{children}</DivContainerSC>
					</MainSC>
				</body>
			</StyledComponentsRegistry>
		</html>
	)
}
