import StyledComponentsRegistry from '@/lib/registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { DivContainerSC, GlobalStyles, MainSC } from './styles.global'
import Header from '@/components/header'
import ReduxProvider from './redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Example Store',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<ReduxProvider>
				<StyledComponentsRegistry>
					<GlobalStyles />
					<body className={inter.className}>
						<Header />
						<MainSC>
							<DivContainerSC>{children}</DivContainerSC>
						</MainSC>
					</body>
				</StyledComponentsRegistry>
			</ReduxProvider>
		</html>
	)
}
